server:
  port: 8090

helix:
  participant:
    instance-name: ${APP_HELIX_INSTANCE_NAME:app_${server.port}}
    zookeeper-address: ${APP_HELIX_ZOOKEPERS:localhost:22181}
    cluster-name: ${APP_HELIX_CLUSTER_NAME:pocHelixCluster}
    hostname: ${HOSTANME:localhost}
    port: ${server.port}

spring:
  jmx:
    enabled: true
    unique-names: true

management:
  metrics:
    enable:
      all: true
  health:
    defaults:
      enabled: true
  server:
    port: 10090
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    jmx:
      domain: alex
      exposure:
        include: "*"
  endpoint:
    jolokia:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true